name: Release CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}

    steps:
      - uses: actions/checkout@v2
      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.get_version.outputs.VERSION }}"
          release_name: "storage ${{ steps.get_version.outputs.VERSION }}"
          body: "See the assets to download this version and install."

  build-ubuntu:
    needs: create-release
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: build image
        run: make

      - name: build application
        run: make build.linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./src-tauri/target/release/bundle/deb/storage_0.0.19_amd64.deb
          tag: "${{ steps.get_version.outputs.VERSION }}"
          release_name: "${{ steps.get_version.outputs.VERSION }}"
          overwrite: true
          file_glob: true
